# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default='5th', max_length=3)),
                ('subject', models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('English', 'English')], default='Science', max_length=20)),
                ('contentType', models.CharField(choices=[('Video', 'Video'), ('Article', 'Article'), ('Other', 'Other')], default='Video', max_length=10)),
                ('chapterNumber', models.CharField(max_length=2)),
                ('contentLink', models.CharField(max_length=1000)),
                ('longDescription', models.CharField(max_length=10000)),
                ('shortDescription', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='boardClass',
        ),
    ]
