# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20170531_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentTitle',
            field=models.CharField(default='NA TITLE', max_length=1000),
        ),
    ]
