# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20170605_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterdetail',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='content',
            name='chapterNumber',
        ),
        migrations.RemoveField(
            model_name='content',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subject',
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='chapterNumber',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='chapterTitle',
            field=models.CharField(default='Title', max_length=300),
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='grade',
            field=models.CharField(choices=[('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default='5th', max_length=3),
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('English', 'English')], default='Science', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aggregator.chapterDetail'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentTitle',
            field=models.CharField(max_length=1000),
        ),
    ]
